# Generated by Django 3.0.4 on 2020-08-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('comment_body', models.TextField(verbose_name='Отзывы')),
                ('comment_name', models.CharField(max_length=50, verbose_name='Введите имя')),
                ('comment_email', models.EmailField(max_length=100, verbose_name='Введите email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('price_work', models.CharField(max_length=100, verbose_name='Наименование работ')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Цена')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('service', models.CharField(max_length=100, verbose_name='Услуга')),
                ('service_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Цена услги')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
