# Generated by Django 3.0.4 on 2020-08-03 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servcie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('subservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='servcie.Service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
