# Generated by Django 3.0.4 on 2020-08-03 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servcie', '0003_subservice_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_price',
        ),
    ]
