# Generated by Django 3.0.4 on 2020-09-18 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servcie', '0005_auto_20200805_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_theme',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Тема'),
            preserve_default=False,
        ),
    ]
