# Generated by Django 3.0.4 on 2020-09-25 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servcie', '0007_comment_comment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['comment_date']},
        ),
    ]
