# Generated by Django 3.0.4 on 2020-09-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servcie', '0008_auto_20200925_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
